import type { Metadata } from "next";

import "./globals.css";

import { JetBrains_Mono } from 'next/font/google';

import HeaderComponent from "@/components/layout/header-component/header-component";
import FooterComponent from "@/components/layout/footer-component/footer-component";
import MainComponent from "@/components/layout/main-component/main-component";

import Providers from "@/stores/providers";
import ReactQueryProvider from "@/stores/react-query-provider";

const layoutFontStyle = JetBrains_Mono({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <Providers>
      <html lang="en">
      <body className={`${layoutFontStyle.className}`}>
        <ReactQueryProvider>
          <HeaderComponent />
          <MainComponent>
            {children}
          </MainComponent>
          <FooterComponent />
        </ReactQueryProvider>
      </body>
      </html>
    </Providers>
  );
}
