name: makstore

services:
  # Databases
  main_db:
    image: postgres
    container_name: main_db.makstore
    environment:
      POSTGRES_USER: rootuser
      POSTGRES_PASSWORD: DbPass20190502
    ports:
      - "9003:5432"
    volumes:
      - main_db_data:/var/lib/postgresql/data
      - ./backups:/backups
    networks:
      - makstore_net
  
  # Microservices  
  auth_service.makstore:
    container_name: auth_service.makstore
    build:
      context: .
      dockerfile: src/MakStore.Microservices/AuthService/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=main_db.makstore;Username=rootuser;Password=DbPass20190502;Database=users_db
      - ConnectionStrings__IdentityServerDb=Host=main_db.makstore;Username=rootuser;Password=DbPass20190502;Database=identity_server_cfg_db
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=sslpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/hostdockerinternal.pfx
    volumes:
      - ./DataProtection-Keys:/DataProtection-Keys
      - ./https:/https
    ports:
      - "9010:80"
      - "9011:443"
    depends_on:
      - main_db
    networks:
      - makstore_net
  
  products_service.makstore:
    container_name: products_service.makstore
    build:
      context: .
      dockerfile: src/MakStore.Microservices/ProductsService/Dockerfile
      args:
        CERT_PATH: ./https/hostdockerinternal.crt
    environment:
      - ActiveConnection=DockerDatabase
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9005:8080"
    depends_on:
      - main_db
    networks:
      - makstore_net
  
  # Client Apps
  employeewebclient.makstore:
    container_name: employeewebclient.makstore
    build:
      context: .
      dockerfile: src/MakStore.ClientApps/EmployeeWebClient/Dockerfile
      args:
        CERT_PATH: ./https/hostdockerinternal.crt
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9002:8080"
    depends_on:
      - auth_service.makstore
    networks:
      - makstore_net
  
  next.makstore:
    container_name: next.makstore
    build:
      context: src/MakStore.ClientApps/makstore
      dockerfile: Dockerfile
    ports:
      - "9001:3000"
    environment:
      - NODE_ENV=production
    depends_on:
        - auth_service.makstore
    networks:
      - makstore_net
  
  # Api Gateway
  api-gateway:
    image: nginx
    container_name: api-gateway.makstore
    ports:
      - "9000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - next.makstore
      - employeewebclient.makstore
    networks:
      - makstore_net

networks:
  makstore_net:
    driver: bridge
    
volumes:
  main_db_data: